export const i18n = {
  pt: {
    // Shared
    project: 'Projeto',
    name: 'Nome',
    description: 'Descrição',
    notes: 'Notas Adicionais',
    type: 'Tipo',
    status: 'Estado',
    
    // Modes
    design: 'Design',
    dev: 'Developer',
    deploy: 'Deploy',

    // App Header
    appTitle: '21 MAKE',
    appSubDesign: 'Gera prompts de UI design',
    appSubDev: 'Gera prompts para AI code editors',
    appSubDeploy: 'Gera prompts para deploy manual',
    
    // Shared Prompt Strings
    promptHeader: '',
    promptFooter: (mode: string) => `*Prompt gerado automaticamente pelo 21 MAKE — Modo ${mode}*`,
    
    // Design Strings
    structure: 'Estrutura',
    pages: 'páginas',
    page: 'Página',
    guidelines: 'Diretrizes Gerais',
    visualStyle: 'Estilo Visual',
    designStyle: 'Estilo de Design',
    colorPalette: 'Paleta de Cores',
    primaryColor: 'Cor Primária',
    mode: 'Modo',
    borderRadius: 'Border Radius',
    density: 'Densidade',
    typography: 'Tipografia',
    layoutNav: 'Layout & Navegação',
    components: 'Componentes UI',
    pagesTitle: 'Páginas / Ecrãs',
    interactions: 'Interações & Feedback',
    toneLang: 'Tom & Linguagem',
    language: 'Idioma',
    qualityRules: 'Regras de Qualidade',
    // Sections
    projectDesc: 'Contexto geral da aplicação',
    styleDesc: 'Estética Visual e Identidade',
    pagesDesc: 'Estrutura de Navegação e Conteúdo',
    interactionsDesc: 'Feedback e UX',
    toneDesc: 'Personalidade e Regras de Qualidade',
    devProjectDesc: 'Contexto técnico e Linguagem',
    stackDesc: 'Frameworks e Bibliotecas',
    patternsDesc: 'Arquitetura e Organização',
    apiDesc: 'Dados e Segurança',
    qualityDesc: 'Linting e Testes',
    automationDesc: 'Workflows e Automatização',
    deployProjectDesc: 'Contexto da aplicação a fazer deploy',
    envDesc: 'Onde vai correr a aplicação',
    containerDesc: 'Plataforma e imagem base',
    buildDesc: 'Como construir e servir',
    networkDesc: 'Portas, proxy reverso e SSL',
    storageDesc: 'Volumes e backups',
    cicdDesc: 'Deploy automático e registries',
    monitorDesc: 'Healthchecks e logging',
    orchestrationDesc: 'Servidor de automação, filas e escalonamento',
    notesDesc: 'Instruções ou contexto extra',
    
    // Dev Strings
    techStack: 'Tech Stack',
    architecture: 'Arquitetura',
    apiData: 'API & Dados',
    qualityTesting: 'Qualidade & Testes',
    aiInstructions: 'Instruções para AI Editor',
    rules: 'Regras de Implementação',
    automationWorkflows: 'Automação & Workflows',

    // Deploy Strings
    environmentOS: 'Ambiente & Sistema Operativo',
    container: 'Container',
    buildRuntime: 'Build & Runtime',
    networking: 'Networking',
    storage: 'Storage & Persistência',
    cicdRegistry: 'CI/CD & Registry',
    monitoring: 'Monitorização',
    deploySteps: 'Passos de Deploy',
    automationOrchestration: 'Automação & Orquestração',

    // Labels & UI
    reset: 'Reset',
    preview: 'Preview',
    copy: 'Copiar',
    save: 'Guardar',
    tokens: 'tokens',
    characters: 'caracteres',
    fieldsFilled: 'campos opcionais preenchidos',
    switchPromptToEnglish: 'Mudar prompt para Inglês',
    switchPromptToPortuguese: 'Mudar prompt para Português',
    inheritedContext: 'Contexto Herdado',
    inheritedDesignDesc: 'O Design definido anteriormente será mapeado automaticamente e herdado nas especificações deste prompt.',
    inheritedDevDesc: 'A Arquitetura e Tech Stack definidos pelo Developer serão injetados automaticamente neste prompt de Deploy.',
    
    // Confirms
    confirmReset: 'Pretendes limpar todos os campos e definições (design, dev, e deploy) do projeto atual?',
  },
  en: {
    // Shared
    project: 'Project',
    name: 'Name',
    description: 'Description',
    notes: 'Additional Notes',
    type: 'Type',
    status: 'Status',

    // Modes
    design: 'Design',
    dev: 'Developer',
    deploy: 'Deploy',

    // App Header
    appTitle: '21 MAKE',
    appSubDesign: 'Generates UI design prompts',
    appSubDev: 'Generates prompts for AI code editors',
    appSubDeploy: 'Generates prompts for manual deployment',

    // Shared Prompt Strings
    promptHeader: '',
    promptFooter: (mode: string) => `*Prompt automatically generated by 21 MAKE — ${mode} Mode*`,

    // Design Strings
    structure: 'Structure',
    pages: 'pages',
    page: 'Page',
    guidelines: 'General Guidelines',
    visualStyle: 'Visual Style',
    designStyle: 'Design Style',
    colorPalette: 'Color Palette',
    primaryColor: 'Primary Color',
    mode: 'Mode',
    borderRadius: 'Border Radius',
    density: 'Density',
    typography: 'Typography',
    layoutNav: 'Layout & Navigation',
    components: 'UI Components',
    pagesTitle: 'Pages / Screens',
    interactions: 'Interactions & Feedback',
    toneLang: 'Tone & Language',
    language: 'Language',
    qualityRules: 'Quality Rules',
    // Sections
    projectDesc: 'General application context',
    styleDesc: 'Visual Aesthetics and Identity',
    pagesDesc: 'Navigation Structure and Content',
    interactionsDesc: 'Feedback and UX',
    toneDesc: 'Personality and Quality Rules',
    devProjectDesc: 'Technical context and Language',
    stackDesc: 'Frameworks and Libraries',
    patternsDesc: 'Architecture and Organization',
    apiDesc: 'Data and Security',
    qualityDesc: 'Linting and Testing',
    automationDesc: 'Workflows and Automation',
    deployProjectDesc: 'Context of the application to deploy',
    envDesc: 'Where the application will run',
    containerDesc: 'Platform and base image',
    buildDesc: 'How to build and serve',
    networkDesc: 'Ports, reverse proxy and SSL',
    storageDesc: 'Volumes and backups',
    cicdDesc: 'Auto-deploy and registries',
    monitorDesc: 'Healthchecks and logging',
    orchestrationDesc: 'Automation server, queues and scaling',
    notesDesc: 'Additional instructions or context',

    // Dev Strings
    techStack: 'Tech Stack',
    architecture: 'Architecture',
    apiData: 'API & Data',
    qualityTesting: 'Quality & Testing',
    aiInstructions: 'AI Editor Instructions',
    rules: 'Implementation Rules',
    automationWorkflows: 'Automation & Workflows',

    // Deploy Strings
    environmentOS: 'Environment & OS',
    container: 'Container',
    buildRuntime: 'Build & Runtime',
    networking: 'Networking',
    storage: 'Storage & Persistence',
    cicdRegistry: 'CI/CD & Registry',
    monitoring: 'Monitoring',
    deploySteps: 'Deploy Steps',
    automationOrchestration: 'Automation & Orchestration',

    // Labels & UI
    reset: 'Reset',
    preview: 'Preview',
    copy: 'Copy',
    save: 'Save',
    tokens: 'tokens',
    characters: 'characters',
    fieldsFilled: 'optional fields filled',
    switchPromptToEnglish: 'Switch prompt to English',
    switchPromptToPortuguese: 'Switch prompt to Portuguese',
    inheritedContext: 'Inherited Context',
    inheritedDesignDesc: 'The Design defined earlier will be automatically mapped and inherited in this prompt\'s specifications.',
    inheritedDevDesc: 'The Architecture and Tech Stack defined by the Developer will be automatically injected into this Deploy prompt.',

    // Confirms
    confirmReset: 'Do you want to clear all fields and settings (design, dev, and deploy) for the current project?',
  },
};

export type Lang = keyof typeof i18n;
