import translations from './locales.json';

export const i18n = {
  pt: {
    ...translations.pt,
    promptFooter: (mode: string) => `*Prompt gerado automaticamente pelo 21 MAKE — Modo ${mode}*`,
    pageDescPlaceholder: (name: string) => `Ex: Ecrã principal com visão geral das métricas, gráficos de atividade e ações rápidas para ${name.toLowerCase()}.`,
    profileConfirmOverwrite: (name: string) => `Tem a certeza que deseja substituir o perfil "${name}" com as configurações atuais?`,
    profileConfirmDelete: (name: string) => `Tem a certeza que deseja eliminar o perfil "${name}"?`,
  },
  en: {
    ...translations.en,
    promptFooter: (mode: string) => `*Prompt automatically generated by 21 MAKE — ${mode} Mode*`,
    pageDescPlaceholder: (name: string) => `Ex: Main screen with metrics overview, activity charts and quick actions for ${name.toLowerCase()}.`,
    profileConfirmOverwrite: (name: string) => `Are you sure you want to overwrite the profile "${name}" with your current settings?`,
    profileConfirmDelete: (name: string) => `Are you sure you want to delete the profile "${name}"?`,
  },
  es: {
    ...translations.es,
    promptFooter: (mode: string) => `*Prompt generado automáticamente por 21 MAKE — Modo ${mode}*`,
    pageDescPlaceholder: (name: string) => `Ej: Pantalla principal con resumen de métricas, gráficos de actividad y acciones rápidas para ${name.toLowerCase()}.`,
    profileConfirmOverwrite: (name: string) => `¿Está seguro de que desea sobrescribir el perfil "${name}" con su configuración actual?`,
    profileConfirmDelete: (name: string) => `¿Está seguro de que desea eliminar el perfil "${name}"?`,
  },
  fr: {
    ...translations.fr,
    promptFooter: (mode: string) => `*Prompt généré automatiquement par 21 MAKE — Mode ${mode}*`,
    pageDescPlaceholder: (name: string) => `Ex: Écran principal avec aperçu des métriques, graphiques d'activité et actions rapides pour ${name.toLowerCase()}.`,
    profileConfirmOverwrite: (name: string) => `Êtes-vous sûr de vouloir écraser le profil "${name}" avec vos paramètres actuels ?`,
    profileConfirmDelete: (name: string) => `Êtes-vous sûr de vouloir supprimer le profil "${name}" ?`,
  }
};

export type Lang = keyof typeof i18n;
